### PR TITLE
feat: add support for configuring separate proxy for HTTPS URLs

### LINKED ISSUE #5: Support separate HTTPS proxy configuration
Instead of having a single env variable for http and https, it would be ideal to have the option of configuring a HTTPS proxy. It's pretty common in enterprise to support HTTP_PROXY, HTTPS_PROXY, NO_PROXY so essentially we're just following that convention in case someone has a different proxy for HTTP and HTTPS.

As background, we'd like to use this package in Renovate Bot, there is a discussion here: https://github.com/renovatebot/renovate/issues/3547

### PR DESCRIPTION
**Pull request by fgreinacher**
Resolves #5

### CODE REVIEW

**Comment by fgreinacher** [comment]
@gajus I cannot run the tests on my Mac (also after trusting the root CA as mentioned in the test output) - they fail with this output:

```
> global-agent@1.1.0 test /Users/fgreinacher/Code/github.com/fgreinacher/global-agent
> NODE_ENV=test nyc ava --verbose --serial


[AnyProxy Log][2019-05-23 20:52:29]: Http proxy started on port 3000
[AnyProxy Log][2019-05-23 20:52:29]: received request to: GET 127.0.0.1/
[AnyProxy Log][2019-05-23 20:52:29]: clearing cache file...
[AnyProxy Log][2019-05-23 20:52:29]: ==>>> clearing cache 
[AnyProxy Log][2019-05-23 20:52:29]: proxy server closed at localhost:3000
[AnyProxy Log][2019-05-23 20:52:29]: Http proxy started on port 3001
[AnyProxy Log][2019-05-23 20:52:29]: received https CONNECT request 127.0.0.1
[AnyProxy Log][2019-05-23 20:52:29]: will forward to local https server
[AnyProxy Log][2019-05-23 20:52:29]: received request to: GET 127.0.0.1/
[AnyProxy Log][2019-05-23 20:52:29]: destorying https connection : 127.0.0.1:49654
[AnyProxy Log][2019-05-23 20:52:29]: closing https cltSocket : 127.0.0.1:49654
[AnyProxy Log][2019-05-23 20:52:29]: clearing cache file...
[AnyProxy Log][2019-05-23 20:52:29]: ==>>> clearing cache 
[AnyProxy Log][2019-05-23 20:52:29]: proxy server closed at localhost:3001
[AnyProxy Log][2019-05-23 20:52:29]: Http proxy started on port 3002
/Users/fgreinacher/Code/github.com/fgreinacher/global-agent/node_modules/brotli/build/encode.js:3
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(x)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},b.readBinary=function(a){if("function"===
                                                                                                                                                                                                                              ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  ✖ test/global-agent/routines/bootstrap.js exited with a non-zero exit code: 7
```

Do you have any ideas on this?

**Comment by fgreinacher** [comment]
OK, a couple of force-pushes later everything is green now :)

@rarkins This should solve the linked issue and allow renovatebot to switch to this library.

**Comment by rarkins** [comment]
@fgreinacher awesome! thank you

**Comment by fgreinacher** [comment]
@gajus any chance to get this in soonish? We’re partially blocked on the renovate issue linked in #5. thanks in advance!

**Comment by rarkins** [comment]
@gajus is there anything holding this back from merge?

**Pull request merged**
