### PR TITLE
Added CA property and method to set and reset it.

### PR DESCRIPTION
**Pull request by vipendra-mehra**
Added CA property and method to set and reset it. 
Also, updated setting rejectUnauthorized property

### CODE REVIEW

**Comment by vipendra-mehra** [comment]
Hope, it gets reviewed and merged soon

**Comment by vipendra-mehra** [comment]
Please review and pull the merge request.
Build is failing due to existing eslint errors.
Please let me know if anything need to be done.

**Comment by vipendra-mehra** [comment]
Hi Team,
If changes are fine, can this pull request be merged?

**Comment by vipendra-mehra** [comment]
Hi Team,
Please review the code changes related to ca property and rejectUnauthorized property

**Comment by vipendra-mehra** [comment]
Coverage check is passed.

Travis Cl - Pull build is failing due to existing eslint errors.
It is failing even for master code as well.

**Comment by vipendra-mehra** [comment]
@gajus pleae review the changes.

**Comment by gajus** [comment]
Need to update README.md to reflect new options.

**Comment by vipendra-mehra** [comment]
@gajus  I have updated README.md to reflect passing of ca property while calling method createGlobalProxyAgent().
Also added ca property type in types.js for the types - ProxyAgentConfigurationInputType and ProxyAgentConfigurationType.
Type TlsConfigurationType was already contain ca as string, I have changed it to object (as ca should be an array and type of array is obejct).

Please review the changes.

**Comment by vipendra-mehra** [comment]
@gajus please have a look.

**Comment by gajus** [comment]
I am not sure if you are still making changes, but earlier feedback was not addressed.

**Comment by vipendra-mehra** [comment]
@gajus I have updated readme.md file to show new option of passing ca as input in createGlobalProxyAgent method.
I have also listed new methods in readme.md file to add and clear ca cert after global agent is initiated.

Please let me know if I have missed to address any of your feedback or any further changes are required.

**Comment by vipendra-mehra** [comment]
@gajus Please review and provide your feedback if anything need to be improved in readme.md file or in code changes

**Pull request closed without merging**
